# Frontend
server {
    listen 80;
    server_name cybernex-team.uz www.cybernex-team.uz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cybernex-team.uz www.cybernex-team.uz;
    ssl_certificate     /etc/letsencrypt/live/cybernex-team.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cybernex-team.uz/privkey.pem;
    client_max_body_size 50M;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host      $server_name;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Backend API
server {
    listen 80;
    server_name api.cybernex-team.uz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.cybernex-team.uz;
    ssl_certificate     /etc/letsencrypt/live/cybernex-team.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cybernex-team.uz/privkey.pem;
    client_max_body_size 50M;

    location / {
        # OPTIONS preflight
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin'      'https://cybernex-team.uz' always;
            add_header 'Access-Control-Allow-Methods'     'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers'     'Authorization, Content-Type, Accept, Origin, X-Requested-With' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age'           1728000;
            add_header 'Content-Length'                   0;
            return 204;
        }

        proxy_pass http://web:8000;

        # $server_name = api.cybernex-team.uz — Django ALLOWED_HOSTS da bor
        proxy_set_header Host              $server_name;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 120s;
        proxy_send_timeout    120s;
        proxy_read_timeout    120s;
    }

    location /media/ {
        alias /app/media/;
    }

    location /staticfiles/ {
        alias /app/staticfiles/;
    }
}