# Frontend
server {
    listen 80;
    server_name cybernex-team.uz www.cybernex-team.uz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cybernex-team.uz www.cybernex-team.uz;
    ssl_certificate     /etc/letsencrypt/live/cybernex-team.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cybernex-team.uz/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }
}

# Backend API
server {
    listen 80;
    server_name api.cybernex-team.uz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.cybernex-team.uz;
    ssl_certificate     /etc/letsencrypt/live/cybernex-team.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cybernex-team.uz/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /media/ {
        alias /app/media/;
    }
}
