# Generated by Django 5.2.6 on 2026-03-22 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uz', models.CharField(max_length=255)),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('stack_uz', models.CharField(max_length=255)),
                ('stack_ru', models.CharField(max_length=255)),
                ('stack_en', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('about_uz', models.TextField(blank=True, null=True)),
                ('about_ru', models.TextField(blank=True, null=True)),
                ('about_en', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content_uz', models.TextField()),
                ('content_ru', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_en', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admin_control.devinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('both', 'Full-time & Part-time')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('achievements_uz', models.TextField(blank=True, null=True)),
                ('achievements_ru', models.TextField(blank=True, null=True)),
                ('achievements_en', models.TextField(blank=True, null=True)),
                ('responsibilities_uz', models.TextField(blank=True, null=True)),
                ('responsibilities_ru', models.TextField(blank=True, null=True)),
                ('responsibilities_en', models.TextField(blank=True, null=True)),
                ('teaching_focus_uz', models.TextField(blank=True, null=True)),
                ('teaching_focus_ru', models.TextField(blank=True, null=True)),
                ('teaching_focus_en', models.TextField(blank=True, null=True)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='admin_control.devinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('technologies', models.JSONField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='admin_control.devinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='admin_control.devinfo')),
            ],
        ),
    ]
