# Generated by Django 5.2.6 on 2026-04-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
