# Generated by Django 5.2.6 on 2026-03-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devinfo',
            old_name='email_en',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='devinfo',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='devinfo',
            name='email_uz',
        ),
    ]
