# Generated by Django 5.2.6 on 2026-04-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0002_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devinfo',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
