# Generated by Django 5.2.6 on 2026-03-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='admin_control.devinfo'),
        ),
        migrations.AddField(
            model_name='project',
            name='dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='admin_control.devinfo'),
        ),
    ]
