# Generated by Django 5.2.6 on 2026-03-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0004_experience_dev_project_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='devinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
