# Generated by Django 5.2.6 on 2026-03-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0006_devinfo_telegram_chat_id_usersinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admin_control.devinfo')),
            ],
        ),
    ]
