# Generated by Django 5.2.6 on 2026-03-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
    ]
